[package]
name = "zet"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
chrono = "0.4"
termimad = "0.25"
serde = "1.0.219"
serde_yaml = "0.9.34"
ratatui = "0.29.0"
crossterm = "0.29.0"
fuzzy-matcher = "0.3.7"
